# -*- coding: utf-8 -*-
"""Stat Arb V&MA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJn3UgwHIMK56V0gFHKw4fOTKeawKWzi
"""

import numpy as np
import pandas as pd
import yfinance as yf
import statsmodels.api as sm
import matplotlib.pyplot as plt
from datetime import datetime

# config and data retrieval
tickers = ['V', 'MA']
start_date = '2023-01-01'
end_date = datetime.now().strftime('%Y-%m-%d')

data = yf.download(tickers, start=start_date, end=end_date, auto_adjust=True)['Close']
display(data.tail())

# calculate hedge ratio using OLS regression
Y = data['V']
X = sm.add_constant(data['MA'])
model = sm.OLS(Y, X).fit()

beta = model.params['MA']
alpha = model.params['const']

# calculate residuals
spread = data['V'] - (beta * data['MA'] + alpha)
print(f'Hedge Ratio: {beta:.4f}')

# normalize spread using Z-score to identify deviations from mean
z_score = (spread - spread.mean()) / np.std(spread)

z_score.plot(figsize=(12, 6), title='Spread Z-Score')
plt.axhline(0, color='black')
plt.axhline(2.0, color='red', linestyle='--')
plt.axhline(-2.0, color='green', linestyle='--')
plt.grid(True, alpha=0.3)
plt.show()

# generate trade entry signals based on Z-score thresholds
def get_signals(z):
    if z > 2.0: return "SELL V / BUY MA"
    if z < -2.0: return "BUY V / SELL MA"
    return None

signals = {date: get_signals(z) for date, z in z_score.items() if abs(z) > 2}
for d, s in list(signals.items())[-5:]:
    print(f"{d.date()}: {s}")

import seaborn as sns

# 1. dual axis price chart
fig, ax1 = plt.subplots(figsize=(14, 7))
ax2 = ax1.twinx()

ax1.plot(data.index, data['V'], color='blue', label='Visa (V)', alpha=0.7)
ax2.plot(data.index, data['MA'], color='orange', label='Mastercard (MA)', alpha=0.7)

ax1.set_xlabel('Date')
ax1.set_ylabel('V Price ($)', color='blue')
ax2.set_ylabel('MA Price ($)', color='orange')
plt.title('Asset Price Comparison: V vs MA')
fig.tight_layout()
plt.show()

import matplotlib.pyplot as plt
# 2. spread distribution and normality
plt.figure(figsize=(10, 6))

plt.axvline(2, color='red', linestyle='--', label='Upper Threshold')
plt.axvline(-2, color='green', linestyle='--', label='Lower Threshold')
plt.title('Distribution of Z-Scores (Look for Mean Reversion)')
plt.legend()
plt.show()

# visualize opportunity zones and threshold boundaries
plt.figure(figsize=(14, 7))
plt.plot(z_score, color='black', lw=1, alpha=0.6)
plt.fill_between(z_score.index, z_score, 2, where=(z_score >= 2), color='red', alpha=0.3)
plt.fill_between(z_score.index, z_score, -2, where=(z_score <= -2), color='green', alpha=0.3)
plt.axhline(2, color='red', linestyle='--', alpha=0.5)
plt.axhline(-2, color='green', linestyle='--', alpha=0.5)
plt.axhline(0, color='blue', alpha=0.8)
plt.title('Trading Opportunity Zones')
plt.show()

total_days = len(z_score)
sell_days = len(z_score[z_score >= 2.0])
buy_days = len(z_score[z_score <= -2.0])
neutral_days = total_days - sell_days - buy_days

# summary table
area_summary = pd.DataFrame({
    'Zone': ['Sell V / Buy MA (Red)', 'Buy V / Sell MA (Green)', 'Neutral (No Trade)'],
    'Days': [sell_days, buy_days, neutral_days],
    'Percentage': [(sell_days/total_days)*100, (buy_days/total_days)*100, (neutral_days/total_days)*100]
})

print(f"Total Trading Days Analyzed: {total_days}")
display(area_summary.round(2))

# exit signals (mean reversion points)
exits = z_score[(z_score.shift(1) > 0) & (z_score <= 0) | (z_score.shift(1) < 0) & (z_score >= 0)].index
print(f"Total Mean Reversion Events: {len(exits)}")

# visualize exits on Z-score chart
plt.figure(figsize=(14, 7))
plt.plot(z_score, label='Z-Score', color='black', alpha=0.5)
plt.scatter(exits, z_score[exits], color='blue', marker='x', label='Mean Reversion (Exit)')

plt.axhline(0, color='blue', linestyle='-', alpha=0.3)
plt.axhline(2, color='red', linestyle='--')
plt.axhline(-2, color='green', linestyle='--')

plt.title('Z-Score with Mean Reversion Exit Points')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

"""### Summary
- **Red**: Short V, Long MA
- **Green**: Long V, Short MA
- **Blue 'x'**: Trade Exit (Spread returned to mean)
"""